### ISSUE TITLE
Hi,my questions are as flow,how can i solve it?

### ISSUE THREAD

**Issue by JIAWENYANG** [ChenYingpeng/caffe-yolov3#10]
![default](https://user-images.githubusercontent.com/16818951/44823456-19be1f80-ac33-11e8-91ce-ec9dd7d428d5.png)

**Comment by JIAWENYANG** [comment]
![2018-08-30 08-59-06](https://user-images.githubusercontent.com/16818951/44823486-483bfa80-ac33-11e8-83e2-7236d1f3a3a5.png)

**Comment by ChenYingpeng** [comment]
May be something wrong with your caffe?Please make sure sucessfully  compile caffe.

**Comment by ChenYingpeng** [comment]
I have update the code,please reload it and make complie it.

**Comment by DeepPower** [comment]
@JIAWENYANG I encountered the same problem as yours.Have you solved it?
