### ISSUE TITLE
Why network is splitted into two in yolov3-tiny?  

### ISSUE THREAD

**Issue by ddkkevin** [ChenYingpeng/caffe-yolov3#29]
There are two prototxt files for caffe yolov3-tiny, namely yolov3-tiny-1.prototxt and yolov3-tiny-2.prototxt.
The network is broken after layer11-conv? However, the yolov3 network is kept as one, why?

**Comment by ChenYingpeng** [comment]
Caffe can not duplicate the layer that maxpool layer (params:kernel_size = 2,stride = 1),so rewrite max_pool_1d function for recurrenting it.

**Comment by ddkkevin** [comment]
I got it，thx
