### ISSUE TITLE
excuse me, the width of detected box is much smaller than the truth box's width, so how to fix this situation?thx! 

### ISSUE THREAD

**Issue by YuBoyang0321151606** [ChenYingpeng/caffe-yolov3#32]
excuse me, the width of detected box is much smaller than the truth box's width, so how to fix this situation?thx!

**Comment by ChenYingpeng** [comment]
@YuBoyang0321151606 Please post the detail of your said.For example,which model you run and  what is the debug info?Thx.

**Comment by YuBoyang0321151606** [comment]
thank you! i fix this problem just now, it's because that the anchor box's size in my dataset are different from original sizes, i reset the anchor sizes and it works. thank you for reply!

**Comment by YuBoyang0321151606** [comment]
@ChenYingpeng

**Comment by YuBoyang0321151606** [comment]
solved
