### ISSUE TITLE
The cudaMemcpy is time consuming

### ISSUE THREAD

**Issue by wywlzyzz** [ChenYingpeng/caffe-yolov3#34]
I added a for loop in the main function to detect images, but the time consumption of cudaMemcpy in the cuda_make_array function located in cuda.cpp increased sharply, about 200 times, after the first detection.

Is there any method to solve this problem? THX.

**Comment by YuBoyang0321151606** [comment]
excuse me, how much time do you cost to detect average picture? @wywlzyzz

**Comment by wywlzyzz** [comment]
I tried yolov3-tiny on gtx1070. For the first image, function get_detections costs about 600ns-700ns, while starting from the second one, get_detections costs about 5000ns for each. Tracking into this function, the time consumption of cudaMemcpy in the cuda_make_array function costs 7ns and 26ns in two yolo layers for the first image, while about **4500ns** and not exceeding 30ns for the rest images.

**Comment by wywlzyzz** [comment]
> excuse me, how much time do you cost to detect average picture? @wywlzyzz

I tried yolov3-tiny on gtx1070. For the first image, function get_detections costs about 600ns-700ns, while starting from the second one, get_detections costs about 5000ns for each. Tracking into this function, the time consumption of cudaMemcpy in the cuda_make_array function costs 7ns and 26ns in two yolo layers for the first image, while about 4500ns and not exceeding 30ns for the rest images.
