### ISSUE TITLE
caffe/caffe.hpp: No such file or directory

### ISSUE THREAD

**Issue by DancingJane** [ChenYingpeng/caffe-yolov3#43]
when I make the project, I met this error

In file included from /home/jane/Files/caffe/include/caffe/caffe.hpp:7:0,
                 from /home/jane/Files/object_detection/caffe-yolov3/yolo_layer.h:9,
                 from /home/jane/Files/object_detection/caffe-yolov3/box.h:9,
                 from /home/jane/Files/object_detection/caffe-yolov3/box.cpp:1:
/home/jane/Files/caffe/include/caffe/blob.hpp:9:34: fatal error: caffe/proto/caffe.pb.h: No such file or directory
compilation terminated.
CMakeFiles/sysDetectSpeed.dir/build.make:107: recipe for target 'CMakeFiles/sysDetectSpeed.dir/box.cpp.o' failed
make[2]: *** [CMakeFiles/sysDetectSpeed.dir/box.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/jane/Files/caffe/include/caffe/caffe.hpp:7:0,
                 from /home/jane/Files/object_detection/caffe-yolov3/yolo_layer.h:9,
                 from /home/jane/Files/object_detection/caffe-yolov3/yolo_layer.cpp:7:
/home/jane/Files/caffe/include/caffe/blob.hpp:9:34: fatal error: caffe/proto/caffe.pb.h: No such file or directory
compilation terminated.
CMakeFiles/sysDetectSpeed.dir/build.make:155: recipe for target 'CMakeFiles/sysDetectSpeed.dir/yolo_layer.cpp.o' failed
make[2]: *** [CMakeFiles/sysDetectSpeed.dir/yolo_layer.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/sysDetectSpeed.dir/all' failed
make[1]: *** [CMakeFiles/sysDetectSpeed.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

could you please help me?

**Comment by sainisanjay** [comment]
Hi @DancingJane how did you solved the issue as i am also facing same issue

**Comment by Existever** [comment]
@DancingJane @sainisanjay 

**we can generate caffe.pb.h by commond 'protoc'**

cd your_caffe_path/include/caffe
mkdir proto
your_caffe_path/src/caffe/proto
protoc --cpp_out=your_caffe_path/include/caffe/proto caffe.proto

**Comment by Existever** [comment]
@DancingJane @sainisanjay

you can generate caffe.pb.h by commond 'protoc'

cd your_caffe_path/include/caffe
mkdir proto
cd your_caffe_path/src/caffe/proto
protoc --cpp_out=your_caffe_path/include/caffe/proto caffe.proto
