### ISSUE TITLE
can train & test own dataset after yolov3 transfer to caffe model ?

### ISSUE THREAD

**Issue by Ashing00** [ChenYingpeng/caffe-yolov3#44]
basically, I use "./x86_64/bin/detectnet 0 ../../data/yolov3/prototxt/yolov3.prototxt ../../data/yolov3/caffemodel/yolov3.caffemodel" to inference original yolov3 model for  coco dataset is ok
the dog.jpg have the correct box.
but when I train my dataset and  do inference ,the result is strange .a lot of boxes appear .my dataset only 10 class .
below picture is the test result.

**Comment by Ashing00** [comment]
I test it on original Yolov3 by darknet is ok,but when transfer the model to caffe and inference
 it is strange.a lot box appear.please help me ,thank you.

![hand](https://user-images.githubusercontent.com/16433957/62843634-e95d7d00-bced-11e9-81be-2f4d90e6e651.jpg)

**Comment by Ashing00** [comment]
sorry,I already found out the solution ,thanks all.

**Comment by RatkoFri** [comment]
@Ashing00  Could you share some detail on how did you adjust YOLO network for your problem?

Ratko
