### ISSUE TITLE
编译的时候出现问题？

### ISSUE THREAD

**Issue by liubianting** [ChenYingpeng/caffe-yolov3#48]
I run make command and face these problem, I don't know how to fix it.
[ 10%] Building NVCC (Device) object CMakeFiles/sysDetectSpeed.dir/sysDetectSpeed_generated_max_pool_1d.cu.o
[ 20%] Building NVCC (Device) object CMakeFiles/sysDetectSpeed.dir/sysDetectSpeed_generated_activation_kernels.cu.o
[ 30%] Building NVCC (Device) object CMakeFiles/sysDetectSpeed.dir/sysDetectSpeed_generated_blas_kernels.cu.o
Scanning dependencies of target sysDetectSpeed
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libgflags.so.2', needed by 'x86_64/lib/libsysDetectSpeed.so'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 40%] Building CXX object CMakeFiles/sysDetectSpeed.dir/box.cpp.o
[ 50%] Building CXX object CMakeFiles/sysDetectSpeed.dir/cuda.cpp.o
[ 60%] Building CXX object CMakeFiles/sysDetectSpeed.dir/image.cpp.o
[ 70%] Building CXX object CMakeFiles/sysDetectSpeed.dir/yolo_layer.cpp.o
/home/administrator/caffe-yolov3/cuda.cpp: In function 'dim3 cuda_gridsize(size_t)':
/home/administrator/caffe-yolov3/cuda.cpp:53:22: warning: narrowing conversion of 'x' from  size_t {aka long unsigned int}' to 'unsigned int' inside { } [-Wnarrowing]
     dim3 d = {x, y, 1};
                      ^
/home/administrator/caffe-yolov3/cuda.cpp:53:22: warning: narrowing conversion of 'y' from  size_t {aka long unsigned int}' to 'unsigned int' inside { } [-Wnarrowing]
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/sysDetectSpeed.dir/all' failed
make[1]: *** [CMakeFiles/sysDetectSpeed.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by liubianting** [comment]
@ChenYingpeng

**Comment by liubianting** [comment]
solved

**Comment by DanielChungYi** [comment]
I got the same problem too, how can I solve it? 
@liubianting @ChenYingpeng

**Comment by liubianting** [comment]
> I got the same problem too, how can I solve it?
> @liubianting @ChenYingpeng

try this https://github.com/ChenYingpeng/caffe-yolov3/issues/6#issuecomment-493833858
