### ISSUE TITLE
把upsample加进caffe之后make出现错误

### ISSUE THREAD

**Issue by liubianting** [ChenYingpeng/caffe-yolov3#49]
[ 87%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/upgrade_proto.cpp.o
[ 87%] Linking CXX shared library ../../lib/libcaffe.so
CMakeFiles/caffe.dir/upsample_layer.cpp.o:(.bss+0x0): multiple definition of `caffe::gInstantiationGuardUpsampleLayer'
CMakeFiles/caffe.dir/layers/upsample_layer.cpp.o:(.bss+0x0): first defined here
CMakeFiles/cuda_compile_1.dir/cuda_compile_1_generated_upsample_layer.cu.o: In function `caffe::translate_idx(int, int, int, int, int)':
tmpxft_000053d8_00000000-5_upsample_layer.cudafe1.cpp:(.text+0x10): multiple definition of `caffe::translate_idx(int, int, int, int, int)'
CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_upsample_layer.cu.o:tmpxft_000052ce_00000000-5_upsample_layer.cudafe1.cpp:(.text+0x10): first defined here
CMakeFiles/cuda_compile_1.dir/cuda_compile_1_generated_upsample_layer.cu.o: In function `caffe::translate_idx_inv(int, int, int, int, int, int, int)':
tmpxft_000053d8_00000000-5_upsample_layer.cudafe1.cpp:(.text+0x30): multiple definition of `caffe::translate_idx_inv(int, int, int, int, int, int, int)'
CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_upsample_layer.cu.o:tmpxft_000052ce_00000000-5_upsample_layer.cudafe1.cpp:(.text+0x30): first defined here
collect2: error: ld returned 1 exit status
src/caffe/CMakeFiles/caffe.dir/build.make:3441: recipe for target 'lib/libcaffe.so.1.0.0' failed

**Comment by liubianting** [comment]
@ChenYingpeng

**Comment by duanyuqi987** [comment]
怎么解决的？
