### ISSUE TITLE
model covert problem

### ISSUE THREAD

**Issue by DanielChungYi** [ChenYingpeng/caffe-yolov3#52]
user@7b114a18e77a:~/daniel_ws/caffe-yolov3-master/model_convert$ python yolov3_darknet2caffe.py yolov3.cfg yolov3.weights yolov3.prototxt yolov3.caffemodel 
  File "yolov3_darknet2caffe.py", line 102
    elif block['type'] == 'upsample':
                                    ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by liubianting** [comment]
缩进不对，修改一下缩进

**Comment by ljh9999** [comment]
Sorry to bother you, I would like to ask if you have used the pre-training weight of darknet53.conv.74 to generate weights files and then convert caffemodel? I had a problem converting my own model. How do you train a model that fits your data set?
