### ISSUE TITLE
大佬，我的电脑上没有cuda如何将cmake里面的cuda去掉啊

### ISSUE THREAD

**Issue by skybocai** [ChenYingpeng/caffe-yolov3#78]
CUDA_CUDART_LIBRARY (ADVANCED)
    linked by target "yolov3-plugin" in directory /home/babi/Documents/caffe-yolov3
    linked by target "demo" in directory /home/babi/Documents/caffe-yolov3/demo
    linked by target "eval" in directory /home/babi/Documents/caffe-yolov3/eval
CUDA_TOOLKIT_INCLUDE (ADVANCED)
   used as include directory in directory /home/babi/Documents/caffe-yolov3
   used as include directory in directory /home/babi/Documents/caffe-yolov3
   used as include directory in directory /home/babi/Documents/caffe-yolov3

**Comment by wycrystal** [comment]
你好，请问你修改好了吗？我电脑上也没有cuda，如果你修改好了，可否告知一下，谢谢！

**Comment by skybocai** [comment]
放弃修改了，我直接改用了有cuda的电脑，如果你修改了可否让我也看一下怎么改的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ChenYingpeng/caffe-yolov3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月19日(星期三) 下午2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ChenYingpeng/caffe-yolov3] 大佬，我的电脑上没有cuda如何将cmake里面的cuda去掉啊 (#78)





 
你好，请问你修改好了吗？我电脑上也没有cuda，如果你修改好了，可否告知一下，谢谢！

**Comment by wycrystal** [comment]
我也放弃了，直接又转换成其它模型测试了

**Comment by alan8122** [comment]
很简单，就是把cuda的实现换成cup的实现，查看caffe的blob.cpp代码就会发现cuda使用的gpu_data() 会有一个cpu_data()对应，因此把YOLO实现中的gpu相关函数换成对应的cpu函数即可，按照这个思路就可以很快改出来

**Comment by skybocai** [comment]
谢谢大佬
